version: "3"
services:
  rails_app:
    container_name: rails_app
    build:
      context: ./video-manager
      dockerfile: ../rails/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./rails/video-manager:/user/src/app
    depends_on:
      - postgres_db
      - sidekiq
    links:
      - postgres_db
      - sidekiq
    expose:
      - "3000"
    ports:
      - "3000:3000"
  postgres:
    image: postgres:9.6
    ports:
     - "5432"
  sidekiq:
    container_name: sidekiq
    build:
      context: ./video-manager
      dockerfile: ../sidekiq/Dockerfile
    command: sidekiq -p 8081 -q critical -q default
    volumes:
      - ./rails/video-manager:/sidekiq
    expose:
      - "8081"
    ports:
      - "8081:8081"
    links:
      - redis
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:4-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data

volumes:

  redis_data:
    driver: local