version: "3"
services:
  rails_app:
    container_name: rails_app
    build:
      context: ./rails
      dockerfile: ./Dockerfile
    volumes:
      - ./video-manager:/usr/src/app:rw
    depends_on:
      - postgres_db
      - redis
    links:
      - redis
      - postgres_db
    expose:
      - "3000"
    ports:
      - "3000:3000"
  postgres_db:
    container_name: postgresql
    image: postgres:9.6
    volumes:
      - ./postgres/data:/var/lib/postgresql:rw
      - ./postgres/docker-entrypoint.d:/usr/local/etc:rw
      - ./postgres/dumps:/db/dumps:ro
    expose:
      - "5432"
    ports:
      - "5432:5432"
  sidekiq:
    container_name: sidekiq
    build:
      context: ./video-manager
      dockerfile: ../sidekiq/Dockerfile
    volumes:
      - ./video-manager:/usr/src/app:rw
    expose:
      - "8081"
    ports:
      - "8081:8081"
    links:
      - rails_app
      - redis
      - postgres_db
    stdin_open: true
    depends_on:
      - rails_app
      - postgres_db
      - redis
  redis:
    container_name: redis
    image: redis:4-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/var/lib/redis/data:rw

volumes:
  redis:
    driver: local
  postgres:
    driver: local
